// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/auth/v1/auth.proto

//go:build protoopaque

package authv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password    string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_KdfSalt     []byte                 `protobuf:"bytes,3,opt,name=kdf_salt,json=kdfSalt,proto3"`
	xxx_hidden_KdfTime     uint32                 `protobuf:"varint,4,opt,name=kdf_time,json=kdfTime,proto3"`
	xxx_hidden_KdfMemoryKb uint32                 `protobuf:"varint,5,opt,name=kdf_memory_kb,json=kdfMemoryKb,proto3"`
	xxx_hidden_KdfThreads  uint32                 `protobuf:"varint,6,opt,name=kdf_threads,json=kdfThreads,proto3"`
	xxx_hidden_WrappedDek  []byte                 `protobuf:"bytes,7,opt,name=wrapped_dek,json=wrappedDek,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegisterRequest) GetKdfSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KdfSalt
	}
	return nil
}

func (x *RegisterRequest) GetKdfTime() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfTime
	}
	return 0
}

func (x *RegisterRequest) GetKdfMemoryKb() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfMemoryKb
	}
	return 0
}

func (x *RegisterRequest) GetKdfThreads() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfThreads
	}
	return 0
}

func (x *RegisterRequest) GetWrappedDek() []byte {
	if x != nil {
		return x.xxx_hidden_WrappedDek
	}
	return nil
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *RegisterRequest) SetKdfSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KdfSalt = v
}

func (x *RegisterRequest) SetKdfTime(v uint32) {
	x.xxx_hidden_KdfTime = v
}

func (x *RegisterRequest) SetKdfMemoryKb(v uint32) {
	x.xxx_hidden_KdfMemoryKb = v
}

func (x *RegisterRequest) SetKdfThreads(v uint32) {
	x.xxx_hidden_KdfThreads = v
}

func (x *RegisterRequest) SetWrappedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_WrappedDek = v
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login       string
	Password    string
	KdfSalt     []byte
	KdfTime     uint32
	KdfMemoryKb uint32
	KdfThreads  uint32
	WrappedDek  []byte
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_KdfSalt = b.KdfSalt
	x.xxx_hidden_KdfTime = b.KdfTime
	x.xxx_hidden_KdfMemoryKb = b.KdfMemoryKb
	x.xxx_hidden_KdfThreads = b.KdfThreads
	x.xxx_hidden_WrappedDek = b.WrappedDek
	return m0
}

type RegisterResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *RegisterResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type LoginRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type LoginResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	xxx_hidden_KdfSalt     []byte                 `protobuf:"bytes,2,opt,name=kdf_salt,json=kdfSalt,proto3"`
	xxx_hidden_KdfTime     uint32                 `protobuf:"varint,3,opt,name=kdf_time,json=kdfTime,proto3"`
	xxx_hidden_KdfMemoryKb uint32                 `protobuf:"varint,4,opt,name=kdf_memory_kb,json=kdfMemoryKb,proto3"`
	xxx_hidden_KdfThreads  uint32                 `protobuf:"varint,5,opt,name=kdf_threads,json=kdfThreads,proto3"`
	xxx_hidden_WrappedDek  []byte                 `protobuf:"bytes,6,opt,name=wrapped_dek,json=wrappedDek,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *LoginResponse) GetKdfSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KdfSalt
	}
	return nil
}

func (x *LoginResponse) GetKdfTime() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfTime
	}
	return 0
}

func (x *LoginResponse) GetKdfMemoryKb() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfMemoryKb
	}
	return 0
}

func (x *LoginResponse) GetKdfThreads() uint32 {
	if x != nil {
		return x.xxx_hidden_KdfThreads
	}
	return 0
}

func (x *LoginResponse) GetWrappedDek() []byte {
	if x != nil {
		return x.xxx_hidden_WrappedDek
	}
	return nil
}

func (x *LoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

func (x *LoginResponse) SetKdfSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KdfSalt = v
}

func (x *LoginResponse) SetKdfTime(v uint32) {
	x.xxx_hidden_KdfTime = v
}

func (x *LoginResponse) SetKdfMemoryKb(v uint32) {
	x.xxx_hidden_KdfMemoryKb = v
}

func (x *LoginResponse) SetKdfThreads(v uint32) {
	x.xxx_hidden_KdfThreads = v
}

func (x *LoginResponse) SetWrappedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_WrappedDek = v
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token       string
	KdfSalt     []byte
	KdfTime     uint32
	KdfMemoryKb uint32
	KdfThreads  uint32
	WrappedDek  []byte
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	x.xxx_hidden_KdfSalt = b.KdfSalt
	x.xxx_hidden_KdfTime = b.KdfTime
	x.xxx_hidden_KdfMemoryKb = b.KdfMemoryKb
	x.xxx_hidden_KdfThreads = b.KdfThreads
	x.xxx_hidden_WrappedDek = b.WrappedDek
	return m0
}

var File_api_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\"\xdf\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bkdf_salt\x18\x03 \x01(\fR\akdfSalt\x12\x19\n" +
	"\bkdf_time\x18\x04 \x01(\rR\akdfTime\x12\"\n" +
	"\rkdf_memory_kb\x18\x05 \x01(\rR\vkdfMemoryKb\x12\x1f\n" +
	"\vkdf_threads\x18\x06 \x01(\rR\n" +
	"kdfThreads\x12\x1f\n" +
	"\vwrapped_dek\x18\a \x01(\fR\n" +
	"wrappedDek\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc1\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bkdf_salt\x18\x02 \x01(\fR\akdfSalt\x12\x19\n" +
	"\bkdf_time\x18\x03 \x01(\rR\akdfTime\x12\"\n" +
	"\rkdf_memory_kb\x18\x04 \x01(\rR\vkdfMemoryKb\x12\x1f\n" +
	"\vkdf_threads\x18\x05 \x01(\rR\n" +
	"kdfThreads\x12\x1f\n" +
	"\vwrapped_dek\x18\x06 \x01(\fR\n" +
	"wrappedDek2\xbf\x01\n" +
	"\vAuthService\x12]\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12Q\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/loginB;Z9github.com/SatzhanDev/gophKeeper/api/proto/auth/v1;authv1b\x06proto3"

var file_api_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: auth.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: auth.v1.RegisterResponse
	(*LoginRequest)(nil),     // 2: auth.v1.LoginRequest
	(*LoginResponse)(nil),    // 3: auth.v1.LoginResponse
}
var file_api_proto_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	2, // 1: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	1, // 2: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	3, // 3: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_auth_v1_auth_proto_init() }
func file_api_proto_auth_v1_auth_proto_init() {
	if File_api_proto_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_v1_auth_proto_rawDesc), len(file_api_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_v1_auth_proto = out.File
	file_api_proto_auth_v1_auth_proto_goTypes = nil
	file_api_proto_auth_v1_auth_proto_depIdxs = nil
}
